image: node:alpine

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - build

build-app:
  stage: build
  script:
    - yarn run build

sast:
  stage: build
include:
  - template: Security/SAST.gitlab-ci.yml
